# Generated by Django 3.1.1 on 2020-09-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20200918_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.CharField(default=1984, max_length=200),
            preserve_default=False,
        ),
    ]
