# Generated by Django 3.1.1 on 2020-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_books_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('book_img', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
