# Generated by Django 3.1.1 on 2020-09-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_booksimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksimages',
            name='book_img',
            field=models.ImageField(upload_to='bookstore/static/'),
        ),
    ]
