# Generated by Django 3.1.1 on 2020-09-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20200920_0114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksImages',
        ),
    ]
